coverage:
  status:
    patch:
      default: false
      lang:
        paths:
          - python/taichi/lang
        target: 70%
    project:
      default: false
      lang:
        paths:
          - python/taichi/lang
        threshold: 2%
