name: Comment Hooks
on:
  issue_comment:
    types: [created, edited]

jobs:
  format:
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request != '' && contains(github.event.comment.body, '/format')
    steps:
      - name: Trigger Format Server
        run: |
          echo curl http://kun.csail.mit.edu:31415/${{ github.event.pull_request.number }} -LO || :

  rebase:
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request != '' && contains(github.event.comment.body, '/rebase')
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: cirrus-actions/rebase@1.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  revert:
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request != '' && contains(github.event.comment.body, '/revert')
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: srt32/revert@v0.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
