name: Persubmit Checks
on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths-ignore:
      - '**.md'
      - '**.rst'
      - '**.txt'
      - 'benchmarks/**'
      - 'examples/**'

jobs:
  code_format:
    name: Code Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check code format
        run: |
          git fetch https://github.com/taichi-dev/taichi.git refs/heads/master
          git reset FETCH_HEAD
          git add .
          git config user.email "taichigardener@gmail.com"
          git config user.name "Taichi Gardener"
          git commit -m "fake squash commit" || true
          git checkout -b last_squash
          git checkout -b enforced_format
          git reset FETCH_HEAD
          pip install --user yapf gitpython
          python misc/format.py
          git add .
          git commit -m "enforce code format" || true
          # exit with 1 if there were differences:
          git diff last_squash enforced_format --exit-code

  build:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Download pre-built LLVM 8.0.1
      run: |
        mkdir taichi-llvm
        cd taichi-llvm
        wget https://github.com/yuanming-hu/taichi_assets/releases/download/llvm8/taichi-llvm-8.0.1-linux-x64.zip --retry-on-http-error=403 --waitretry=3 --tries=5
        unzip taichi-llvm-8.0.1.zip

    - name: Build Taichi
      env:
        CC: clang++
        CXX: clang++
        PYTHON: python
        PYTHON_VERSION: 3.8
      run: |
        export TAICHI_REPO_DIR=`pwd`
        export PATH=$TAICHI_REPO_DIR/bin:$PATH
        export PATH=$TAICHI_REPO_DIR/taichi-llvm/bin/:$PATH
        export PYTHONPATH=$TAICHI_REPO_DIR/python
        python misc/ci_setup.py ci
        ti test -vr2 -t2
