name: Persubmit Checks
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build_and_test:
    name: Build and Test
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'skip ci') && github.event.sender.login != 'taichi-gardener' }}
    strategy:
      matrix:
        os: [windows-latest]
        python: [3.8]
        with_cc: [OFF]
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.with_cc == 'ON' }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Download Pre-Built LLVM 10.0.0
        run: |
          python misc/ci_download.py
        env:
          CI_PLATFORM: ${{ matrix.os }}

      - name: Build Project
        run: |
          python misc/ci_build.py
        env:
          CI_PLATFORM: ${{ matrix.os }}
          CI_SETUP_CMAKE_ARGS: -DTI_WITH_OPENGL:BOOL=OFF -DTI_WITH_CC:BOOL=${{ matrix.with_cc }}

      - name: Functionallity Test
        run: |
          export TAICHI_REPO_DIR=`pwd`
          export PATH=$TAICHI_REPO_DIR/bin:$PATH
          export PATH=$TAICHI_REPO_DIR/taichi-llvm/bin/:$PATH
          export PYTHONPATH=$TAICHI_REPO_DIR/python
          python examples/laplace.py
          ti test -vr2 -t2
