name: Taichi Gardener
on:
  pull_request:
    types: [review_requested, synchronize]

jobs:
  format:
    name: Trigger Format Server
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.pull_request.requested_reviewers, 'taichi-gardener') }}
    steps:
      - run: |
          echo curl http://kun.csail.mit.edu:31415/${{ github.event.pull_request.number }} -LO
